#allinfo about the action
name: 'make gh-pages branch'
description: 'This action creates a gh-pages branch for a repository and pushes the rocrates to it'
author: 'Decruw Cedric'
branding:
  icon: 'git-branch'
  color: 'blue'
inputs:
  token:
    description: 'Github secret token for the repository'
    required: true
    default: '${{ secrets.GITHUB_TOKEN }}'
  config:
    description: 'Path to the config file'
    required: true
    default: './config.yml'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.config }}