name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Pip Setup
      run: pip install -r requirements.txt

    - name: Run Python unit tests
      run: python3 -u -m unittest tests/tests.py

    - name: Verify that the Docker image for the action builds
      run: docker build . --file Dockerfile

    - name: Build HTML File Test
      id: integration
      uses: ./
      with:
        crate_path: ./tests/test_crate/.
        loglevel: DEBUG

    - name: Archive test HTML
      id: save_artifact
      uses: actions/upload-artifact@v3
      with:
        name: html-test-build
        path: ./tests/test_crate/*.html
        retention-days: 2

    - name: Verify integration test results
      run: python3 -u -m unittest tests/integration.py
